///POST http://127.0.0.1:3000/auth/register
///Content-Type: application/json

///{
///    "name":"prueba",
///    "email":"pan@gmail.com",
///    "password":"123456"
/// }

###login
POST http://127.0.0.1:3000/auth/login
Content-Type: application/json

{
    "name":"prueba2",
    "email":"pan@gmail.com",
    "password":"1234567"
}

###users y agragar el toquen
GET http://127.0.0.1:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlkIjoxLCJpYXQiOjE3MTU4NzM3MTgsImV4cCI6MTcxNTg3Mzg2OH0.lInwo-TipIZLvI8TnI9RzQ7DZ8kOQ5NRibR3tHykzAw